import { createContext, useContext } from 'react';

export type AppLanguage = 'en' | 'ru';

export const languageStorageKey = 'app-language';

const englishText = {
  account: 'Account',
  accountAndGoalSettings: 'Account and goal settings',
  accountAndGoalSettingsDescription:
    'Manage the account session and see the limits currently enabled in the app.',
  accountCreated: 'Account created. If Supabase asks for confirmation, check your email.',
  accountDetails: 'Account details',
  achievementStats: 'Achievement stats',
  achievements: 'Achievements',
  active: 'Active',
  activeGoals: 'Active goals',
  aiMentor: 'AI mentor',
  answerAllQuickQuestions: 'Answer all quick questions and save them first.',
  answerFewQuestions: 'Answer a few quick questions',
  answerQuickQuestionsFirst: 'Answer the quick questions first.',
  answersEnough: 'Three or four answers are enough to make the roadmap more useful.',
  answersSavedNext: 'Answers saved. Next: create the roadmap below.',
  answersSavedOpening: 'Answers saved. Opening the roadmap.',
  archived: 'Archived',
  askForHelp: 'Ask for help',
  askMentorPlaceholder: 'Ask the mentor about this goal...',
  askShortQuestion: 'Ask one short question. The mentor will answer using your goal and roadmap.',
  askTheMentor: 'Ask for the next step',
  authDescription: 'Sign in or create an account to save goals, plans, and mentor chat history.',
  authMode: 'Authentication mode',
  averageProgress: 'Average progress',
  availableTime: 'Available time',
  back: 'Back',
  badges: 'Badges',
  cancel: 'Cancel',
  changePlan: 'Change plan',
  checkingMessages: 'Checking saved messages for this goal.',
  checkingRoadmap: 'Checking roadmap...',
  completed: 'Completed',
  completedTasks: 'Completed tasks',
  createAccount: 'Create account',
  createAccountTitle: 'Create your account',
  createGoal: 'Create goal',
  createGoalDescription:
    'Add the basics now. The mentor will ask a few short questions next.',
  createGoalLimit: (maxGoals: number) =>
    `You can create up to ${maxGoals} goals. Keep working with your current goals.`,
  createGoalLimitReached: 'Goal limit reached',
  createGoalLimitReachedDescription: (maxGoals: number) =>
    `You can track up to ${maxGoals} goals right now. Delete one current goal to create a new one.`,
  createRoadmap: 'Create roadmap',
  createRoadmapToGetTask: 'Create a roadmap to get your first task.',
  currentLevel: 'Current level',
  currentLevelPlaceholder: 'Beginner, tried a few times, or know the basics',
  dateRequired: 'Choose a date.',
  dayInARow: 'Day in a row',
  daysInARow: 'Days in a row',
  delete: 'Delete',
  deleting: 'Deleting...',
  description: 'Description',
  descriptionPlaceholder: 'What result do you want?',
  disabled: 'Disabled',
  doThisNext: 'Do this next',
  draft: 'Draft',
  duePrefix: 'due',
  enabled: 'Enabled',
  finisher: 'Finisher',
  finisherText: 'Complete one goal.',
  firstDirection: 'First direction',
  firstGoal: 'First goal',
  firstGoalText: 'Create your first learning goal.',
  focus: 'Focus',
  focusTime: 'Focus time',
  goalDeletion: 'Goal deletion',
  goalDetails: 'Goal details',
  goalInfo: 'Goal info',
  goalLimit: 'Goal limit',
  goalNotFoundOrDeleted: 'Goal not found or already deleted.',
  goalPage: 'Goal page',
  goalStack: 'Goal stack',
  goalStackText: 'Track three goals at the same time.',
  goalTitle: 'Goal title',
  goalTitleHelp: 'Write a little more, at least 3 characters.',
  goalTitlePlaceholder: 'Example: learn to solve a Rubik cube',
  goals: 'Goals',
  guidanceVoice: 'Guidance voice',
  history: 'History',
  historyActions: 'History and actions',
  hours: 'hours',
  iAmStuck: "I'm stuck",
  language: 'Language',
  languagePair: 'Russian / English',
  level: 'Level',
  loading: 'Loading...',
  loadingChat: 'Loading chat...',
  loadingGoal: 'goal',
  loadingGoals: 'Loading goals...',
  loadingGoalsDescription: 'Preparing your list.',
  loadingMentor: 'mentor',
  loadingQuestions: 'questions',
  loadingReady: 'ready',
  loadingSavedStages: 'Loading saved stages and question answers.',
  loadingStages: 'stages',
  loadingTasks: 'tasks',
  locked: 'Locked',
  markDone: 'Mark done',
  maxGoalsValue: (maxGoals: number) => `${maxGoals} goals`,
  mentor: 'Mentor',
  mentorLabel: 'Mentor',
  mentorReady: 'Mentor ready',
  mentorShapes: 'This mentor shapes the questions, roadmap, and AI chat.',
  min: 'min',
  myGoals: 'My goals',
  mainNavigation: 'Main navigation',
  navAchievements: 'Achievements',
  navGoals: 'Goals',
  navMentor: 'AI Mentor',
  navMentorCharacters: 'Mentors',
  navProgress: 'Progress',
  navRoadmap: 'Roadmap',
  navSettings: 'Settings',
  navTasks: 'Tasks',
  navToday: 'Today',
  newGoal: 'New goal',
  noAchievements: 'No achievements yet',
  noAchievementsDescription: 'Create a goal and complete your first task to unlock progress badges.',
  noDate: 'No date',
  noDateSelected: 'No date selected',
  noGoal: 'No goal',
  noGoalFound: 'Goal not found',
  noGoalFoundDescription:
    'It may have been deleted or is unavailable for the current user.',
  noGoalSelected: 'No goal selected',
  noGoalSelectedDescription:
    'Create a goal first, then this tab will open the matching goal section.',
  noGoals: 'No goals yet',
  noGoalsDescription:
    'Describe what you want to learn. The AI mentor will prepare a clear first step.',
  noRoadmapYet: 'No roadmap yet',
  notProvided: 'Not provided',
  notifications: 'Notifications',
  off: 'Off',
  open: 'Open',
  openGoal: 'Open goal',
  openGoals: 'Open goals',
  openRoadmap: 'Open roadmap',
  optionalNote: 'Optional note',
  overallProgress: 'Overall progress',
  password: 'Password',
  passwordPlaceholder: 'At least 6 characters',
  paused: 'Paused',
  perDay: 'per day',
  perWeek: 'per week',
  plan: 'Plan',
  planReady: 'Plan ready',
  prepareList: 'Preparing the list.',
  progress: 'Progress',
  progressHistory: 'Progress history',
  promoEnter: 'Enter',
  question: 'Question',
  questionsStuckHelpChat: 'Questions, stuck help, and chat',
  readyToCreate: 'Ready to create',
  reason: 'Reason',
  refineDescription: 'You can refine the description before creating the plan.',
  retry: 'Retry',
  retryAnswer: 'Retry answer',
  retrying: 'Retrying...',
  roadmap: 'Roadmap',
  roadmapActionDescription:
    'The mentor will turn your goal and answers into stages and first tasks.',
  roadmapAfterQuestions: 'Answer the quick questions, then create the roadmap here.',
  roadmapPreview: 'Roadmap preview',
  roadmapReadyDescription: 'Press the button below and the AI mentor will build the plan.',
  saveAndOpenRoadmap: 'Save and open roadmap',
  saveAnswers: 'Save answers',
  saveAnswersFirst: 'Save your answers above, then come back here to create the roadmap.',
  savedGoalDescription: 'You can clarify this before generating the plan.',
  saving: 'Saving...',
  selected: 'Selected',
  selectedMentor: 'Selected mentor',
  send: 'Send',
  settings: 'Settings',
  settingsDescription: 'Adjust your account, language, palette, and hidden path preferences.',
  settingsEyebrow: 'Sanctuary controls',
  signIn: 'Sign in',
  signInRequired: 'You need to sign in.',
  signInTitle: 'Sign in',
  signOut: 'Sign out',
  signUp: 'Sign up',
  signedIn: 'Signed in.',
  signedInAs: 'Signed in as',
  signingInWait: 'Please wait...',
  smallestActionToday: 'This is the smallest useful action for today.',
  startedMoving: 'Started moving',
  startedMovingText: 'Make progress on any goal.',
  starterPlan: 'Starter plan',
  status: 'Status',
  streak: 'Streak',
  summary: 'Summary',
  stuckAdaptationDescription:
    'The mentor suggests changes first. Nothing is applied automatically.',
  stuckAdaptationTitle: 'Get a lighter version of the plan',
  successCriteria: 'Success criteria',
  suggestAdaptation: 'Suggest adaptation',
  target: 'Target',
  targetDate: 'Target date',
  targetDateAria: 'Choose goal target date',
  themePair: 'Light / dark theme',
  thisWeek: 'This week',
  thinking: 'Thinking...',
  time: 'Time',
  timePeriod: 'Time unit',
  timePeriodDay: 'Per day',
  timePeriodWeek: 'Per week',
  timePositive: 'Enter a number greater than zero.',
  today: 'Today',
  todayQuestion: 'What is the next step?',
  todayTaskFallback: 'Create a roadmap to get your first task.',
  todaysNextStep: "Today's next step",
  totalGoals: 'Total goals',
  unlocked: 'Unlocked',
  unlockingTasksDescription:
    'Answer the quick questions, then create your roadmap to unlock tasks.',
  unknownError: 'Unknown error',
  useMentorWhenStuck: 'Use this when a task feels unclear or you want a smaller action.',
  weeklyStats: 'Weekly stats',
  whatNextEmpty: 'Create your first goal and the mentor will suggest a small step.',
  whatNextGoal: 'Open this goal and create the roadmap.',
  wordBox: 'Promo',
  wordBoxPlaceholder: 'Type promo words...',
  workspaceTools: 'Workspace tools',
  searchYourPath: 'Search your path',
  pursueGoal: 'Pursue goal',
  globalPreferences: 'Global preferences',
  displayMode: 'Display mode',
  brandEyebrow: 'Your magical journey',
  userRole: 'Pathfinder',
  yourAnswer: 'Your answer',
  yourProgressBadges: 'Your progress badges',
  yourProgressBadgesDescription:
    'Badges unlock as you create goals, finish tasks, and build momentum.',
  you: 'You',
} as const;

type EnglishText = typeof englishText;

export type TextDictionary = {
  [Key in keyof EnglishText]: EnglishText[Key] extends (...args: infer Args) => string
    ? (...args: Args) => string
    : string;
};

const russianText: TextDictionary = {
  accountDetails: 'Данные аккаунта',
  brandEyebrow: 'Твой путь к цели',
  displayMode: 'Режим экрана',
  globalPreferences: 'Общие настройки',
  guidanceVoice: 'Голос подсказок',
  hours: 'ч',
  languagePair: 'Русский / English',
  mainNavigation: 'Главная навигация',
  mentorLabel: 'Наставник',
  notifications: 'Уведомления',
  openRoadmap: 'Открыть карту',
  pursueGoal: 'Вперед к цели',
  roadmapPreview: 'Предпросмотр пути',
  searchYourPath: 'Поиск по пути',
  settingsDescription: 'Настрой аккаунт, язык, палитру и скрытые опции.',
  settingsEyebrow: 'Панель управления',
  status: 'Статус',
  themePair: 'Светлая / темная тема',
  userRole: 'Исследователь',
  workspaceTools: 'Инструменты',
  account: 'Аккаунт',
  accountAndGoalSettings: 'Настройки аккаунта и целей',
  accountAndGoalSettingsDescription:
    'Управляй сессией аккаунта и смотри лимиты, которые сейчас включены в приложении.',
  accountCreated: 'Аккаунт создан. Если Supabase попросит подтверждение, проверь почту.',
  achievementStats: 'Статистика достижений',
  achievements: 'Достижения',
  active: 'Активна',
  activeGoals: 'Активные цели',
  aiMentor: 'AI-наставник',
  answerAllQuickQuestions: 'Ответь на все быстрые вопросы и сохрани ответы.',
  answerFewQuestions: 'Ответь на несколько быстрых вопросов',
  answerQuickQuestionsFirst: 'Сначала ответь на быстрые вопросы.',
  answersEnough: 'Трёх или четырёх ответов достаточно, чтобы сделать план полезнее.',
  answersSavedNext: 'Ответы сохранены. Следующий шаг: создай дорожную карту ниже.',
  answersSavedOpening: 'Ответы сохранены. Открываем дорожную карту.',
  archived: 'Архив',
  askForHelp: 'Попросить помощь',
  askMentorPlaceholder: 'Спроси наставника про эту цель...',
  askShortQuestion: 'Задай один короткий вопрос. Наставник ответит с учётом цели и плана.',
  askTheMentor: 'Спроси следующий шаг',
  authDescription: 'Войди или создай аккаунт, чтобы сохранять цели, планы и чат с наставником.',
  authMode: 'Режим входа',
  averageProgress: 'Средний прогресс',
  availableTime: 'Свободное время',
  back: 'Назад',
  badges: 'Награды',
  cancel: 'Отмена',
  changePlan: 'Изменить план',
  checkingMessages: 'Проверяем сохранённые сообщения по этой цели.',
  checkingRoadmap: 'Проверяем дорожную карту...',
  completed: 'Завершена',
  completedTasks: 'Выполнено задач',
  createAccount: 'Создать аккаунт',
  createAccountTitle: 'Создай аккаунт',
  createGoal: 'Создать цель',
  createGoalDescription:
    'Добавь основу. Потом наставник задаст несколько коротких вопросов.',
  createGoalLimit: (maxGoals: number) =>
    `Можно создать максимум ${maxGoals} целей. Продолжай работу с текущими целями.`,
  createGoalLimitReached: 'Лимит целей достигнут',
  createGoalLimitReachedDescription: (maxGoals: number) =>
    `Сейчас можно вести максимум ${maxGoals} целей. Удали одну текущую цель, чтобы создать новую.`,
  createRoadmap: 'Создать дорожную карту',
  createRoadmapToGetTask: 'Создай дорожную карту, чтобы получить первое задание.',
  currentLevel: 'Текущий уровень',
  currentLevelPlaceholder: 'Новичок, пробовал пару раз или знаю основы',
  dateRequired: 'Выбери дату.',
  dayInARow: 'День подряд',
  daysInARow: 'Дней подряд',
  delete: 'Удалить',
  deleting: 'Удаляем...',
  description: 'Описание',
  descriptionPlaceholder: 'Какой результат ты хочешь получить?',
  disabled: 'Выключено',
  doThisNext: 'Сделай это дальше',
  draft: 'Черновик',
  duePrefix: 'до',
  enabled: 'Включено',
  finisher: 'Финишер',
  finisherText: 'Заверши одну цель.',
  firstDirection: 'Первое направление',
  firstGoal: 'Первая цель',
  firstGoalText: 'Создай первую учебную цель.',
  focus: 'Фокус',
  focusTime: 'Время фокуса',
  goalDeletion: 'Удаление целей',
  goalDetails: 'Детали цели',
  goalInfo: 'Информация о цели',
  goalLimit: 'Лимит целей',
  goalNotFoundOrDeleted: 'Цель не найдена или уже удалена.',
  goalPage: 'Страница цели',
  goalStack: 'Стек целей',
  goalStackText: 'Веди три цели одновременно.',
  goalTitle: 'Название цели',
  goalTitleHelp: 'Напиши чуть подробнее, минимум 3 символа.',
  goalTitlePlaceholder: 'Например: научиться собирать кубик Рубика',
  goals: 'Цели',
  history: 'История',
  historyActions: 'История и действия',
  iAmStuck: 'Я застрял',
  language: 'Язык',
  level: 'Уровень',
  loading: 'Загрузка...',
  loadingChat: 'Загружаем чат...',
  loadingGoal: 'цель',
  loadingGoals: 'Загрузка целей...',
  loadingGoalsDescription: 'Подготавливаем список.',
  loadingMentor: 'наставник',
  loadingQuestions: 'вопросы',
  loadingReady: 'готово',
  loadingSavedStages: 'Загружаем сохранённые этапы и ответы.',
  loadingStages: 'этапы',
  loadingTasks: 'задачи',
  locked: 'Закрыто',
  markDone: 'Отметить выполненным',
  maxGoalsValue: (maxGoals: number) => `${maxGoals} целей`,
  mentor: 'Наставник',
  mentorReady: 'Наставник готов',
  mentorShapes: 'Этот наставник влияет на вопросы, дорожную карту и AI-чат.',
  min: 'мин',
  myGoals: 'Мои цели',
  navAchievements: 'Достижения',
  navGoals: 'Цели',
  navMentor: 'AI-наставник',
  navMentorCharacters: '\u041d\u0430\u0441\u0442\u0430\u0432\u043d\u0438\u043a\u0438',
  navProgress: 'Прогресс',
  navRoadmap: 'Дорожная карта',
  navSettings: 'Настройки',
  navTasks: 'Задачи',
  navToday: 'Сегодня',
  newGoal: 'Новая цель',
  noAchievements: 'Достижений пока нет',
  noAchievementsDescription: 'Создай цель и выполни первое задание, чтобы открыть награды.',
  noDate: 'Без даты',
  noDateSelected: 'Дата не выбрана',
  noGoal: 'Нет цели',
  noGoalFound: 'Цель не найдена',
  noGoalFoundDescription:
    'Возможно, она была удалена или недоступна текущему пользователю.',
  noGoalSelected: 'Цель не выбрана',
  noGoalSelectedDescription:
    'Сначала создай цель, потом эта вкладка откроет нужный раздел.',
  noGoals: 'Пока нет целей',
  noGoalsDescription:
    'Опиши, чему хочешь научиться. AI-наставник подготовит первый понятный шаг.',
  noRoadmapYet: 'Дорожной карты пока нет',
  notProvided: 'Не указано',
  off: 'Выкл.',
  open: 'Открыть',
  openGoal: 'Открыть цель',
  openGoals: 'Открыть цели',
  optionalNote: 'Комментарий',
  overallProgress: 'Общий прогресс',
  password: 'Пароль',
  passwordPlaceholder: 'Минимум 6 символов',
  paused: 'Пауза',
  perDay: 'в день',
  perWeek: 'в неделю',
  plan: 'План',
  planReady: 'План готов',
  prepareList: 'Подготавливаем список.',
  progress: 'Прогресс',
  progressHistory: 'История прогресса',
  promoEnter: 'Ввести',
  question: 'Вопрос',
  questionsStuckHelpChat: 'Вопросы, помощь и чат',
  readyToCreate: 'Можно создавать',
  reason: 'Причина',
  refineDescription: 'Описание можно уточнить перед созданием плана.',
  retry: 'Повторить',
  retryAnswer: 'Повторить ответ',
  retrying: 'Повторяем...',
  roadmap: 'Дорожная карта',
  roadmapActionDescription:
    'Наставник превратит цель и ответы в этапы и первые задания.',
  roadmapAfterQuestions: 'Ответь на быстрые вопросы, потом создай дорожную карту здесь.',
  roadmapReadyDescription: 'Нажми кнопку ниже, и AI-наставник соберёт план.',
  saveAndOpenRoadmap: 'Сохранить и открыть план',
  saveAnswers: 'Сохранить ответы',
  saveAnswersFirst: 'Сохрани ответы выше, потом вернись сюда и создай дорожную карту.',
  savedGoalDescription: 'Это можно уточнить перед генерацией плана.',
  saving: 'Сохраняем...',
  selected: 'Выбрано',
  selectedMentor: 'Выбранный наставник',
  send: 'Отправить',
  settings: 'Настройки',
  signIn: 'Войти',
  signInRequired: 'Нужно войти в аккаунт.',
  signInTitle: 'Войти',
  signOut: 'Выйти',
  signUp: 'Регистрация',
  signedIn: 'Вход выполнен.',
  signedInAs: 'Вошёл как',
  signingInWait: 'Подождите...',
  smallestActionToday: 'Это самый маленький полезный шаг на сегодня.',
  startedMoving: 'Начал движение',
  startedMovingText: 'Сделай прогресс по любой цели.',
  starterPlan: 'Стартовый план',
  streak: 'Серия',
  summary: 'Сводка',
  stuckAdaptationDescription:
    'Наставник сначала предложит изменения. План не изменится автоматически.',
  stuckAdaptationTitle: 'Получить более лёгкую версию плана',
  successCriteria: 'Критерии успеха',
  suggestAdaptation: 'Предложить адаптацию',
  target: 'Срок',
  targetDate: 'Желаемый срок',
  targetDateAria: 'Выбор желаемого срока цели',
  thisWeek: 'На этой неделе',
  thinking: 'Думаем...',
  time: 'Время',
  timePeriod: 'Единица времени',
  timePeriodDay: 'В день',
  timePeriodWeek: 'В неделю',
  timePositive: 'Укажи число больше нуля.',
  today: 'Сегодня',
  todayQuestion: 'Какой следующий шаг?',
  todayTaskFallback: 'Создай дорожную карту, чтобы получить первое задание.',
  todaysNextStep: 'Следующий шаг сегодня',
  totalGoals: 'Всего целей',
  unlocked: 'Открыто',
  unlockingTasksDescription:
    'Ответь на быстрые вопросы, потом создай дорожную карту, чтобы открыть задания.',
  unknownError: 'Неизвестная ошибка',
  useMentorWhenStuck: 'Используй это, если задание непонятно или нужен шаг поменьше.',
  weeklyStats: 'Статистика недели',
  whatNextEmpty: 'Создай первую цель, и наставник предложит маленький шаг.',
  whatNextGoal: 'Открой цель и создай дорожную карту.',
  wordBox: 'Промо',
  wordBoxPlaceholder: 'Введи промо-слова...',
  yourAnswer: 'Твой ответ',
  yourProgressBadges: 'Твои награды прогресса',
  yourProgressBadgesDescription:
    'Награды открываются, когда ты создаёшь цели, выполняешь задания и двигаешься вперёд.',
  you: 'Ты',
};

export const text: Record<AppLanguage, TextDictionary> = {
  en: englishText,
  ru: russianText,
};

export type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  t: TextDictionary;
};

export const LanguageContext = createContext<LanguageContextValue | null>(null);

export function getInitialLanguage(): AppLanguage {
  try {
    const savedLanguage = localStorage.getItem(languageStorageKey);

    return savedLanguage === 'ru' ? 'ru' : 'en';
  } catch {
    return 'en';
  }
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }

  return context;
}
