import { createContext, useContext } from 'react';

export type AppLanguage = 'en' | 'ru';

export const languageStorageKey = 'app-language';

export const text = {
  en: {
    account: 'Account',
    accountAndGoalSettings: 'Account and goal settings',
    accountAndGoalSettingsDescription:
      'Manage the account session and see the limits currently enabled in the app.',
    achievementStats: 'Achievement stats',
    achievements: 'Achievements',
    active: 'Active',
    activeGoals: 'Active goals',
    aiMentor: 'AI mentor',
    archived: 'Archived',
    averageProgress: 'Average progress',
    badges: 'Badges',
    cancel: 'Cancel',
    completed: 'Completed',
    createGoal: 'Create goal',
    createGoalDescription:
      'Fill in the basics. In the next steps, AI will ask clarifying questions.',
    createGoalLimit: (maxGoals: number) =>
      `You can create up to ${maxGoals} goals. Keep working with your current goals.`,
    createGoalLimitReached: 'Goal limit reached',
    createGoalLimitReachedDescription: (maxGoals: number) =>
      `You can track up to ${maxGoals} goals right now. Delete one current goal to create a new one.`,
    currentLevel: 'Current level',
    currentLevelPlaceholder: 'For example: beginner, tried a few times, know the basics',
    dateRequired: 'Choose a date.',
    dayInARow: 'Day in a row',
    daysInARow: 'Days in a row',
    delete: 'Delete',
    deleting: 'Deleting...',
    description: 'Description',
    descriptionPlaceholder: 'What exactly do you want to get as a result?',
    disabled: 'Disabled',
    draft: 'Draft',
    duePrefix: 'due',
    enabled: 'Enabled',
    finisher: 'Finisher',
    finisherText: 'Complete one goal.',
    firstGoal: 'First goal',
    firstGoalText: 'Create your first learning goal.',
    focus: 'Focus',
    focusTime: 'Focus time',
    goalDeletion: 'Goal deletion',
    goalLimit: 'Goal limit',
    goalStack: 'Goal stack',
    goalStackText: 'Track three goals at the same time.',
    goalTitle: 'Goal title',
    goalTitleHelp: 'Write a little more, at least 3 characters.',
    goalTitlePlaceholder: 'For example: learn to solve a Rubik’s cube',
    goals: 'Goals',
    loading: 'Loading...',
    loadingGoals: 'Loading goals...',
    loadingGoalsDescription: 'Preparing the list.',
    locked: 'Locked',
    maxGoalsValue: (maxGoals: number) => `${maxGoals} goals`,
    myGoals: 'My goals',
    navAchievements: 'Achievements',
    navGoals: 'Goals',
    navMentor: 'AI Mentor',
    navProgress: 'Progress',
    navRoadmap: 'Roadmap',
    navSettings: 'Settings',
    navTasks: 'Tasks',
    navToday: 'Today',
    newGoal: 'New goal',
    noGoal: 'No goal',
    noGoalSelected: 'No goal selected',
    noGoalSelectedDescription: 'Create a goal first, then this sidebar tab will open the matching goal feature.',
    noGoalFound: 'Goal not found',
    noGoalFoundDescription: 'It may have been deleted or is unavailable for the current user.',
    noGoals: 'No goals yet',
    noGoalsDescription:
      'Describe what you want to learn. The AI mentor will prepare the first clear step.',
    off: 'Off',
    open: 'Open',
    openGoal: 'Open goal',
    openGoals: 'Open goals',
    overallProgress: 'Overall progress',
    paused: 'Paused',
    prepareList: 'Preparing the list.',
    progress: 'Progress',
    promoEnter: 'Enter',
    savedGoalDescription: 'You can clarify the description before generating the plan.',
    settings: 'Settings',
    signedInAs: 'Signed in as',
    signOut: 'Sign out',
    startedMoving: 'Started moving',
    startedMovingText: 'Make progress on any goal.',
    streak: 'Streak',
    targetDate: 'Target date',
    targetDateAria: 'Choose goal target date',
    thisWeek: 'This week',
    timePeriod: 'Time unit',
    timePeriodDay: 'Per day',
    timePeriodWeek: 'Per week',
    timePositive: 'Enter a number greater than zero.',
    today: 'Today',
    todayQuestion: 'What are we working on today?',
    todayTaskFallback: 'The task will appear after creating a plan',
    totalGoals: 'Total goals',
    unlocked: 'Unlocked',
    weeklyStats: 'Weekly stats',
    whatNextEmpty: 'Create your first goal, and the AI mentor will suggest a small step for today.',
    whatNextGoal: 'Open the goal and create a roadmap.',
    wordBox: 'Promo',
    wordBoxPlaceholder: 'Type promo words...',
    yourProgressBadges: 'Your progress badges',
    yourProgressBadgesDescription: 'These badges are calculated from the goals saved in your app.',
  },
  ru: {
    account: 'Аккаунт',
    accountAndGoalSettings: 'Настройки аккаунта и целей',
    accountAndGoalSettingsDescription:
      'Управляй сессией аккаунта и смотри лимиты, которые сейчас включены в приложении.',
    achievementStats: 'Статистика достижений',
    achievements: 'Достижения',
    active: 'Активна',
    activeGoals: 'Активные цели',
    aiMentor: 'AI-наставник',
    archived: 'Архив',
    averageProgress: 'Средний прогресс',
    badges: 'Награды',
    cancel: 'Отмена',
    completed: 'Завершена',
    createGoal: 'Создать цель',
    createGoalDescription:
      'Заполни основу. На следующих этапах AI будет задавать уточняющие вопросы.',
    createGoalLimit: (maxGoals: number) =>
      `Можно создать максимум ${maxGoals} целей. Продолжай работу с текущими целями.`,
    createGoalLimitReached: 'Лимит целей достигнут',
    createGoalLimitReachedDescription: (maxGoals: number) =>
      `Сейчас можно вести максимум ${maxGoals} целей. Удали одну из текущих целей, чтобы создать новую.`,
    currentLevel: 'Текущий уровень',
    currentLevelPlaceholder: 'Например: новичок, уже пробовал пару раз, знаю основы',
    dateRequired: 'Выбери дату.',
    dayInARow: 'День подряд',
    daysInARow: 'Дней подряд',
    delete: 'Удалить',
    deleting: 'Удаляем...',
    description: 'Описание',
    descriptionPlaceholder: 'Что именно ты хочешь получить в результате?',
    disabled: 'Выключено',
    draft: 'Черновик',
    duePrefix: 'до',
    enabled: 'Включено',
    finisher: 'Финишер',
    finisherText: 'Заверши одну цель.',
    firstGoal: 'Первая цель',
    firstGoalText: 'Создай первую учебную цель.',
    focus: 'Фокус',
    focusTime: 'Время фокуса',
    goalDeletion: 'Удаление целей',
    goalLimit: 'Лимит целей',
    goalStack: 'Стек целей',
    goalStackText: 'Веди три цели одновременно.',
    goalTitle: 'Название цели',
    goalTitleHelp: 'Напиши цель чуть подробнее, минимум 3 символа.',
    goalTitlePlaceholder: 'Например: научиться собирать кубик Рубика',
    goals: 'Цели',
    loading: 'Загрузка...',
    loadingGoals: 'Загрузка целей...',
    loadingGoalsDescription: 'Подготавливаем список.',
    locked: 'Закрыто',
    maxGoalsValue: (maxGoals: number) => `${maxGoals} целей`,
    myGoals: 'Мои цели',
    navAchievements: 'Достижения',
    navGoals: 'Цели',
    navMentor: 'AI-наставник',
    navProgress: 'Прогресс',
    navRoadmap: 'Дорожная карта',
    navSettings: 'Настройки',
    navTasks: 'Задачи',
    navToday: 'Сегодня',
    newGoal: 'Новая цель',
    noGoal: 'Нет цели',
    noGoalSelected: 'Цель не выбрана',
    noGoalSelectedDescription: 'Сначала создай цель, потом эта вкладка откроет нужный раздел.',
    noGoalFound: 'Цель не найдена',
    noGoalFoundDescription: 'Возможно, она была удалена или недоступна текущему пользователю.',
    noGoals: 'Пока нет целей',
    noGoalsDescription:
      'Опиши, чему хочешь научиться. AI-наставник подготовит первый понятный шаг.',
    off: 'Выкл.',
    open: 'Открыть',
    openGoal: 'Открыть цель',
    openGoals: 'Открыть цели',
    overallProgress: 'Общий прогресс',
    paused: 'Пауза',
    prepareList: 'Подготавливаем список.',
    progress: 'Прогресс',
    promoEnter: 'Enter',
    savedGoalDescription: 'Описание можно будет уточнить перед генерацией плана.',
    settings: 'Настройки',
    signedInAs: 'Вошёл как',
    signOut: 'Выйти',
    startedMoving: 'Начал движение',
    startedMovingText: 'Сделай прогресс по любой цели.',
    streak: 'Серия',
    targetDate: 'Желаемый срок',
    targetDateAria: 'Выбор желаемого срока цели',
    thisWeek: 'На этой неделе',
    timePeriod: 'Единица времени',
    timePeriodDay: 'В день',
    timePeriodWeek: 'В неделю',
    timePositive: 'Укажи число больше нуля.',
    today: 'Сегодня',
    todayQuestion: 'Что делаем сегодня?',
    todayTaskFallback: 'Задание появится после создания плана',
    totalGoals: 'Всего целей',
    unlocked: 'Открыто',
    weeklyStats: 'Статистика недели',
    whatNextEmpty: 'Создай первую цель, и AI-наставник предложит маленький шаг на сегодня.',
    whatNextGoal: 'Открой цель и создай дорожную карту.',
    wordBox: 'Promo',
    wordBoxPlaceholder: 'Type promo words...',
    yourProgressBadges: 'Твои награды прогресса',
    yourProgressBadgesDescription: 'Эти награды считаются по целям, сохранённым в приложении.',
  },
} as const;

export type TextDictionary = (typeof text)[AppLanguage];

export type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  t: TextDictionary;
};

export const LanguageContext = createContext<LanguageContextValue | null>(null);

export function getInitialLanguage(): AppLanguage {
  const savedLanguage = localStorage.getItem(languageStorageKey);

  return savedLanguage === 'ru' || savedLanguage === 'en' ? savedLanguage : 'en';
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }

  return context;
}
