export const CASE_OPENING_CONFIG = {
  ANIMATION_DURATION_MS: 5800,
  SCROLL_SPEED_PX_PER_SEC: 1180,
  CARD_SPACING_PX: 14,
  CARD_WIDTH_PX: 128,
  VISIBLE_CARD_COUNT: 5,
  EASING_TYPE: 'easeOutQuint',
  WINNING_ITEM_POSITION: 2,
  BOUNCE_AMOUNT_PX: 18,
  ACCELERATION_RATIO: 0.1,
  DECELERATION_RATIO: 0.28,
  BOUNCE_DURATION_MS: 420,
} as const;

export type ReelEasingType = (typeof CASE_OPENING_CONFIG)['EASING_TYPE'];
